#!/usr/bin/env node

import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const defaultRepoRoot = fileURLToPath(new URL('../..', import.meta.url));
const generatedTokensPath = 'src/design/tokens.ts';
const sourceTokensPath = 'design-tokens.json';
const optionalGeneratedCssPath = 'tokens.css';
const rawDesignCssPath = 'docs/design/v1/raw/tokens.css';

function repoRelative(repoRoot, path) {
  return relative(repoRoot, path).replaceAll('\\', '/');
}

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

function toCamelCase(key) {
  return key.replace(/-([a-z0-9])/g, (_match, char) => char.toUpperCase());
}

function normalizeDimension(value) {
  const match = /^(-?\d+(?:\.\d+)?)(pt|px|ms)$/.exec(value);

  if (!match) {
    return value;
  }

  return Number(match[1]);
}

function normalizeTokenValue(value) {
  if (typeof value === 'string') {
    return normalizeDimension(value);
  }

  if (Array.isArray(value)) {
    return value.map(normalizeTokenValue);
  }

  if (!value || typeof value !== 'object') {
    return value;
  }

  return Object.fromEntries(
    Object.entries(value).map(([key, child]) => [toCamelCase(key), normalizeTokenValue(child)]),
  );
}

function normalizeTokenGroup(group) {
  if (Array.isArray(group) || !group || typeof group !== 'object') {
    return normalizeTokenValue(group);
  }

  if ('$value' in group) {
    return normalizeTokenValue(group.$value);
  }

  return Object.fromEntries(
    Object.entries(group)
      .filter(([key]) => !key.startsWith('$'))
      .map(([key, value]) => [toCamelCase(key), normalizeTokenGroup(value)]),
  );
}

function numberContract(contract, key) {
  const value = contract?.[key];

  if (typeof value !== 'number') {
    throw new Error(`design-tokens.json contract.${key} must be a number`);
  }

  return value;
}

function buildBusinessTokens(contract) {
  return {
    noStreaksDays: numberContract(contract, 'no-streaks-days'),
    quickLogPosition: contract['quick-log-position'],
    quickLogTrackersMax: numberContract(contract, 'quick-log-trackers-max'),
    tabs: contract.tabs,
    timing: {
      accidentalDoubleTapWindowSeconds: numberContract(
        contract,
        'accidental-double-tap-window-seconds',
      ),
      duplicateCareWarningWindowSeconds: numberContract(
        contract,
        'duplicate-warning-window-seconds',
      ),
    },
    todayDailyCardsMax: numberContract(contract, 'today-daily-cards-max'),
  };
}

function normalizeTypography(sourceTypography) {
  const typography = normalizeTokenGroup(sourceTypography);

  typography.scale = Object.fromEntries(
    Object.entries(typography.scale ?? {}).map(([key, style]) => [
      key,
      {
        ...style,
        letterSpacing: style.letterSpacing ?? 0,
      },
    ]),
  );

  return typography;
}

export function buildTokenPayload(source) {
  return {
    business: buildBusinessTokens(source.contract ?? {}),
    color: normalizeTokenGroup(source.color),
    component: normalizeTokenGroup(source.component),
    elevation: normalizeTokenGroup(source.elevation),
    haptic: normalizeTokenGroup(source.haptic),
    icon: normalizeTokenGroup(source.icon),
    layout: normalizeTokenGroup(source.layout),
    motion: normalizeTokenGroup(source.motion),
    radius: normalizeTokenGroup(source.radius),
    space: normalizeTokenGroup(source.space),
    typography: normalizeTypography(source.typography),
  };
}

export function renderTokensModule(payload) {
  return `// Generated by scripts/design/generate-tokens.mjs. Do not edit directly.
// Source: design-tokens.json.

export const tokens = ${JSON.stringify(payload, null, 2)} as const;

export const businessTiming = tokens.business.timing;

export type DesignTokens = typeof tokens;
export type BusinessTimingTokens = typeof businessTiming;
`;
}

function flattenCssLeaves(value, path = []) {
  if (Array.isArray(value)) {
    return [];
  }

  if (!value || typeof value !== 'object') {
    return [[path, value]];
  }

  return Object.entries(value).flatMap(([key, child]) => flattenCssLeaves(child, [...path, key]));
}

function toKebabCase(key) {
  return key.replace(/[A-Z]/g, (char) => `-${char.toLowerCase()}`);
}

function cssVariablePath(path) {
  return path.map(toKebabCase).join('-');
}

function cssValue(group, path, value) {
  if (typeof value === 'number') {
    if (group === 'motion' && path[0] === 'duration') {
      return `${value}ms`;
    }

    if (group === 'typography' && path.at(-1) === 'fontWeight') {
      return String(value);
    }

    return `${value}px`;
  }

  return String(value);
}

function normalizeCssComparisonValue(value) {
  return String(value)
    .trim()
    .replace(/\s*,\s*/g, ',')
    .replace(/\s+/g, ' ');
}

function normalizeGeneratedFile(value) {
  return String(value).replace(/\r\n?/g, '\n');
}

function readCssCustomProperties(css) {
  const properties = new Map();
  const propertyPattern = /(--[A-Za-z0-9_-]+)\s*:\s*([^;]+);/g;

  for (const match of css.matchAll(propertyPattern)) {
    properties.set(match[1], normalizeCssComparisonValue(match[2]));
  }

  return properties;
}

function rawDesignCssVariables(payload) {
  const px = (value) => (value === undefined ? undefined : `${value}px`);
  const cssLength = (value) => (value === 0 ? '0' : `${value}px`);
  const quoteFont = (font) => {
    const keywordFonts = new Set([
      '-apple-system',
      'BlinkMacSystemFont',
      'Menlo',
      'monospace',
      'sans-serif',
      'serif',
      'system-ui',
      'ui-monospace',
    ]);

    return keywordFonts.has(font) ? font : `"${font}"`;
  };
  const fontFamily = (...fonts) => fonts.filter(Boolean).map(quoteFont).join(', ');
  const monoFonts = (payload.typography.fontFamily?.mono ?? []).flatMap((font) =>
    font === 'monospace' ? ['ui-monospace', 'Menlo', font] : [font],
  );
  const elevationShadow = (elevation) =>
    elevation
      ? `${cssLength(elevation.x)} ${cssLength(elevation.y)} ${cssLength(elevation.blur)} ${elevation.color}`
      : undefined;

  return Object.fromEntries(
    Object.entries({
      '--pp-accent-100': payload.color.accent?.[100],
      '--pp-accent-300': payload.color.accent?.[300],
      '--pp-accent-500': payload.color.accent?.[500],
      '--pp-accent-700': payload.color.accent?.[700],
      '--pp-danger': payload.color.status?.danger,
      '--pp-danger-tint': payload.color.status?.dangerTint,
      '--pp-focus-ring': payload.color.stroke?.focusRing,
      '--pp-info': payload.color.status?.info,
      '--pp-info-tint': payload.color.status?.infoTint,
      '--pp-pill-completed-fill': payload.color.pill?.completed?.fill,
      '--pp-pill-completed-text': payload.color.pill?.completed?.text,
      '--pp-pill-confirmed-fill': payload.color.pill?.confirmed?.fill,
      '--pp-pill-confirmed-text': payload.color.pill?.confirmed?.text,
      '--pp-pill-failed-fill': payload.color.pill?.failed?.fill,
      '--pp-pill-failed-text': payload.color.pill?.failed?.text,
      '--pp-pill-pending-fill': payload.color.pill?.pending?.fill,
      '--pp-pill-pending-text': payload.color.pill?.pending?.text,
      '--pp-pill-review-fill': payload.color.pill?.needsVetReview?.fill,
      '--pp-pill-review-text': payload.color.pill?.needsVetReview?.text,
      '--pp-pill-template-fill': payload.color.pill?.template?.fill,
      '--pp-pill-template-text': payload.color.pill?.template?.text,
      '--pp-pill-urgent-fill': payload.color.pill?.urgent?.fill,
      '--pp-pill-urgent-text': payload.color.pill?.urgent?.text,
      '--pp-primary-50': payload.color.primary?.[50],
      '--pp-primary-100': payload.color.primary?.[100],
      '--pp-primary-200': payload.color.primary?.[200],
      '--pp-primary-300': payload.color.primary?.[300],
      '--pp-primary-400': payload.color.primary?.[400],
      '--pp-primary-500': payload.color.primary?.[500],
      '--pp-primary-600': payload.color.primary?.[600],
      '--pp-primary-700': payload.color.primary?.[700],
      '--pp-primary-800': payload.color.primary?.[800],
      '--pp-primary-900': payload.color.primary?.[900],
      '--pp-r-sm': px(payload.radius.sm),
      '--pp-r-md': px(payload.radius.md),
      '--pp-r-lg': px(payload.radius.lg),
      '--pp-r-full': px(payload.radius.full),
      '--pp-s-1': px(payload.space[1]),
      '--pp-s-2': px(payload.space[2]),
      '--pp-s-3': px(payload.space[3]),
      '--pp-s-4': px(payload.space[4]),
      '--pp-s-5': px(payload.space[5]),
      '--pp-s-6': px(payload.space[6]),
      '--pp-s-8': px(payload.space[8]),
      '--pp-s-10': px(payload.space[10]),
      '--pp-s-14': px(payload.space[14]),
      '--pp-stroke': payload.color.stroke?.default,
      '--pp-stroke-strong': payload.color.stroke?.strong,
      '--pp-stroke-hair': payload.color.stroke?.dividerHairline,
      '--pp-success': payload.color.status?.success,
      '--pp-success-tint': payload.color.status?.successTint,
      '--pp-surface-base': payload.color.surface.base,
      '--pp-surface-overlay': payload.color.surface.overlay,
      '--pp-surface-raised': payload.color.surface.raised,
      '--pp-surface-scrim': payload.color.surface.scrim,
      '--pp-surface-sunken': payload.color.surface.sunken,
      '--pp-text-disabled': payload.color.text.disabled,
      '--pp-text-link': payload.color.text.link,
      '--pp-text-on-accent': payload.color.text.onAccent,
      '--pp-text-on-primary': payload.color.text.onPrimary,
      '--pp-text-primary': payload.color.text.primary,
      '--pp-text-secondary': payload.color.text.secondary,
      '--pp-text-tertiary': payload.color.text.tertiary,
      '--pp-warning': payload.color.status?.warning,
      '--pp-warning-tint': payload.color.status?.warningTint,
      '--pp-elev-0': payload.elevation?.[0] ? '0 0 0 1px var(--pp-stroke)' : undefined,
      '--pp-elev-1': payload.elevation?.[1]
        ? `${elevationShadow(payload.elevation[1])}, 0 0 0 1px var(--pp-stroke)`
        : undefined,
      '--pp-elev-2': elevationShadow(payload.elevation?.[2]),
      '--pp-elev-3': elevationShadow(payload.elevation?.[3]),
      '--pp-font': fontFamily(
        '-apple-system',
        'BlinkMacSystemFont',
        payload.typography.fontFamily?.ios,
        'SF Pro Display',
        'system-ui',
        payload.typography.fontFamily?.android,
        'sans-serif',
      ),
      '--pp-font-mono': monoFonts.length > 0 ? fontFamily(...monoFonts) : undefined,
    }).filter(([, value]) => value !== undefined),
  );
}

function checkRawDesignCssDrift(path, payload, repoRoot) {
  const actual = readCssCustomProperties(readFileSync(path, 'utf8'));
  const errors = [];

  for (const [variable, expected] of Object.entries(rawDesignCssVariables(payload))) {
    const actualValue = actual.get(variable);
    const expectedValue = normalizeCssComparisonValue(expected);

    if (actualValue === undefined) {
      errors.push(`${variable} is missing`);
      continue;
    }

    if (actualValue !== expectedValue) {
      errors.push(`${variable} is ${actualValue}, expected ${expectedValue}`);
    }
  }

  if (errors.length > 0) {
    throw new Error(`${repoRelative(repoRoot, path)} drift: ${errors.join('; ')}`);
  }
}

export function renderTokensCss(payload) {
  const cssRoots = {
    color: payload.color,
    layout: payload.layout,
    motion: payload.motion,
    radius: payload.radius,
    space: payload.space,
    typography: payload.typography,
  };
  const lines = [
    '/* Generated by scripts/design/generate-tokens.mjs. Do not edit directly. */',
    ':root {',
  ];

  for (const [group, value] of Object.entries(cssRoots)) {
    for (const [path, leaf] of flattenCssLeaves(value)) {
      if (typeof leaf === 'object') {
        continue;
      }

      lines.push(`  --pp-${group}-${cssVariablePath(path)}: ${cssValue(group, path, leaf)};`);
    }
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

export function writeGeneratedTokens({ repoRoot = defaultRepoRoot, source = null } = {}) {
  const sourceTokens = source ?? readJson(join(repoRoot, sourceTokensPath));
  const payload = buildTokenPayload(sourceTokens);
  const output = renderTokensModule(payload);
  const outputPath = join(repoRoot, generatedTokensPath);

  mkdirSync(join(repoRoot, 'src/design'), { recursive: true });
  writeFileSync(outputPath, output);

  return {
    output,
    outputPath,
    payload,
  };
}

export function checkTokenDrift({ repoRoot = defaultRepoRoot } = {}) {
  const source = readJson(join(repoRoot, sourceTokensPath));
  const payload = buildTokenPayload(source);
  const expectedModule = renderTokensModule(payload);
  const actualModulePath = join(repoRoot, generatedTokensPath);

  if (!existsSync(actualModulePath)) {
    throw new Error(`${generatedTokensPath} drift: generated token module is missing`);
  }

  const actualModule = readFileSync(actualModulePath, 'utf8');
  if (normalizeGeneratedFile(actualModule) !== normalizeGeneratedFile(expectedModule)) {
    throw new Error(`${generatedTokensPath} drift: run npm run tokens:generate`);
  }

  const checkedCss = [];
  const generatedCssPath = join(repoRoot, optionalGeneratedCssPath);
  if (existsSync(generatedCssPath)) {
    const actualCss = readFileSync(generatedCssPath, 'utf8');
    const expectedCss = renderTokensCss(payload);

    if (normalizeGeneratedFile(actualCss) !== normalizeGeneratedFile(expectedCss)) {
      throw new Error(`${optionalGeneratedCssPath} drift: run npm run tokens:generate and update CSS`);
    }

    checkedCss.push(repoRelative(repoRoot, generatedCssPath));
  }

  const rawCssPath = join(repoRoot, rawDesignCssPath);
  if (existsSync(rawCssPath)) {
    checkRawDesignCssDrift(rawCssPath, payload, repoRoot);
    checkedCss.push(repoRelative(repoRoot, rawCssPath));
  }

  return {
    checkedCss,
    checkedModule: repoRelative(repoRoot, actualModulePath),
  };
}

function runCli() {
  const checkOnly = process.argv.includes('--check');

  if (checkOnly) {
    const result = checkTokenDrift();
    const cssStatus = result.checkedCss.length > 0 ? `css=${result.checkedCss.join(',')}` : 'css=absent';
    console.log(`design tokens ok: ts=${result.checkedModule} ${cssStatus}`);
    return;
  }

  const result = writeGeneratedTokens();
  console.log(`generated ${repoRelative(defaultRepoRoot, result.outputPath)}`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  runCli();
}
