export const QUICK_LOG_ACCIDENTAL_DOUBLE_TAP_WINDOW_SECONDS = 3;
export const QUICK_LOG_DUPLICATE_CARE_WARNING_WINDOW_SECONDS = 60;

export const QUICK_LOG_ACCIDENTAL_DOUBLE_TAP_WINDOW_MS =
  QUICK_LOG_ACCIDENTAL_DOUBLE_TAP_WINDOW_SECONDS * 1000;
export const QUICK_LOG_DUPLICATE_CARE_WARNING_WINDOW_MS =
  QUICK_LOG_DUPLICATE_CARE_WARNING_WINDOW_SECONDS * 1000;

export const quickLogTiming = {
  accidentalDoubleTapWindowSeconds: QUICK_LOG_ACCIDENTAL_DOUBLE_TAP_WINDOW_SECONDS,
  duplicateCareWarningWindowSeconds: QUICK_LOG_DUPLICATE_CARE_WARNING_WINDOW_SECONDS,
} as const;
