import type { I18nKey } from '@/lib/i18n';

export const primaryTabs = [
  {
    id: 'diary',
    routeName: 'diary/index',
    href: '/diary',
    labelKey: 'tabs.diary',
    accessibilityLabelKey: 'tabs.diary-hint',
  },
  {
    id: 'pet',
    routeName: 'pet/index',
    href: '/pet',
    labelKey: 'tabs.pet',
    accessibilityLabelKey: 'tabs.pet-hint',
  },
  {
    id: 'more',
    routeName: 'more/index',
    href: '/more',
    labelKey: 'tabs.more',
    accessibilityLabelKey: 'tabs.more',
  },
] as const satisfies readonly {
  id: string;
  routeName: string;
  href: string;
  labelKey: I18nKey;
  accessibilityLabelKey: I18nKey;
}[];

export const quickLogAction = {
  id: 'quick-log',
  href: '/quick-log',
  labelKey: 'tabs.quick-log-fab-label',
  accessibilityHintKey: 'tabs.quick-log-fab-hint',
} as const satisfies {
  id: string;
  href: string;
  labelKey: I18nKey;
  accessibilityHintKey: I18nKey;
};

export const scheduleAction = {
  id: 'schedule',
  href: '/quick-log/schedule',
  labelKey: 'nav.schedule-slab',
  accessibilityHintKey: 'nav.schedule-fab-hint',
} as const satisfies {
  id: string;
  href: string;
  labelKey: I18nKey;
  accessibilityHintKey: I18nKey;
};

export const settingsRoutes = [
  '/settings/puppy-profile',
  '/settings/quick-trackers',
  '/settings/household',
  '/settings/sitter-mode',
  '/settings/notifications',
  '/settings/help',
] as const;

export const modalRoutes = [
  quickLogAction.href,
  scheduleAction.href,
  '/quick-log/details',
  '/paywall',
  '/reminders/edit',
  '/family/invite',
  '/sharing/trainer-preview',
  '/sharing/scope-selector',
  '/sharing/puppy-card',
  '/pet/health-record-edit',
  '/pet/health-record/[recordId]',
  ...settingsRoutes,
] as const;

export const developmentOnlyRoutes = ['/_dev/components'] as const;

export const deepLinkPlaceholders = ['/invite/[token]', '/share/[token]'] as const;

export const atlasRouteAliases = {
  '/today': '/diary',
  '/health': '/pet',
  '/timeline': '/diary',
  '/more/puppy-profile': '/settings/puppy-profile',
} as const satisfies Record<string, string>;

export const plannedRouteFiles = [
  {
    route: '/diary',
    file: 'app/(tabs)/diary/index.tsx',
    implementationStage: 'existing',
  },
  {
    route: '/pet',
    file: 'app/(tabs)/pet/index.tsx',
    implementationStage: 'existing',
  },
  {
    route: '/today',
    file: 'app/(tabs)/today/index.tsx',
    implementationStage: 'existing',
  },
  {
    route: '/health',
    file: 'app/(tabs)/health/index.tsx',
    implementationStage: 'existing',
  },
  {
    route: '/onboarding',
    file: 'app/onboarding/index.tsx',
    implementationStage: 'existing',
  },
  {
    route: '/invite/[token]',
    file: 'app/invite/[token].tsx',
    implementationStage: 'existing',
  },
  {
    route: '/share/[token]',
    file: 'app/share/[token].tsx',
    implementationStage: 'existing',
  },
  {
    route: '/settings/puppy-profile',
    file: 'app/(modals)/settings/puppy-profile/index.tsx',
    implementationStage: 'existing',
  },
  {
    route: '/settings/quick-trackers',
    file: 'app/(modals)/settings/quick-trackers/index.tsx',
    implementationStage: 'existing',
  },
  {
    route: '/settings/household',
    file: 'app/(modals)/settings/household/index.tsx',
    implementationStage: 'existing',
  },
  {
    route: '/settings/sitter-mode',
    file: 'app/(modals)/settings/sitter-mode/index.tsx',
    implementationStage: 'existing',
  },
  {
    route: '/settings/notifications',
    file: 'app/(modals)/settings/notifications/index.tsx',
    implementationStage: 'existing',
  },
  {
    route: '/settings/help',
    file: 'app/(modals)/settings/help/index.tsx',
    implementationStage: 'existing',
  },
  {
    route: '/paywall',
    file: 'app/(modals)/paywall/index.tsx',
    implementationStage: 'existing',
  },
  {
    route: '/sharing/puppy-card',
    file: 'app/(modals)/sharing/puppy-card/index.tsx',
    implementationStage: 'existing',
  },
  {
    route: '/quick-log/schedule',
    file: 'app/(sheets)/quick-log/schedule/index.tsx',
    implementationStage: 'existing',
  },
  {
    route: '/pet/health-record-edit',
    file: 'app/(modals)/pet/health-record-edit/index.tsx',
    implementationStage: 'existing',
  },
  {
    route: '/pet/health-record/[recordId]',
    file: 'app/(modals)/pet/health-record/[recordId].tsx',
    implementationStage: 'existing',
  },
  {
    route: '/reminders/edit',
    file: 'app/(modals)/reminders/edit/index.tsx',
    implementationStage: 'existing',
  },
  {
    route: '/_dev/components',
    file: 'app/_dev/components.tsx',
    implementationStage: 'existing',
  },
] as const satisfies readonly {
  route: string;
  file: string;
  implementationStage: 'existing' | 'planned';
}[];

export const shellI18nKeys = [
  'common.back',
  'common.close',
  'common.loading',
  'errors.load-failed',
  'tabs.diary',
  'tabs.diary-hint',
  'tabs.pet',
  'tabs.pet-hint',
  'tabs.more',
  'tabs.add',
  'tabs.add-close',
  'tabs.quick-log-fab-label',
  'tabs.quick-log-fab-hint',
  'nav.quick-log-slab',
  'nav.quick-log-slab-subtitle',
  'nav.schedule-slab',
  'nav.schedule-slab-subtitle',
  'nav.schedule-fab-hint',
  'states.empty-first-run.title',
  'states.empty-first-run.body',
  'today.quick-log.unavailable.title',
  'today.quick-log.unavailable.body',
  'today.quick-log.timeline-entry',
  'today.quick-log.setup-entry',
  'today.quick-log.section-title',
  'today.quick-log.empty.title',
  'today.quick-log.empty.body',
  'today.states.all-done.status',
  'today.states.all-done.title',
  'today.states.all-done.body',
  'today.states.cold-start.title',
  'today.states.cold-start.body',
  'today.states.empty-history.title',
  'today.states.empty-history.body',
  'today.history.section-title',
  'today.history.open-action',
  'today.history.delete-action',
  'today.history.item-actions',
  'today.history.fact-a11y-label',
  'timeline.filter-chips.0',
  'timeline.filter-chips.1',
  'timeline.filter-chips.2',
  'timeline.filter-chips.3',
  'timeline.section-today',
  'timeline.section-yesterday',
  'timeline.section-date',
  'timeline.empty-filter',
  'today.week-strip.label',
  'today.week-strip.day-label',
  'today.week-strip.state-default',
  'today.week-strip.state-selected',
  'today.week-strip.state-today',
  'today.week-strip.state-selected-today',
  'onboarding.first-log.body-after-first',
  'onboarding.first-log.eyebrow',
  'onboarding.first-log.event-title',
  'onboarding.first-log.event-meta',
  'onboarding.first-log.hero-after-first',
  'onboarding.first-log.today-title',
  'timeline.pills.pending',
  'timeline.pills.failed',
  'timeline.pills.synced',
  'timeline.actor-you',
  'timeline.row-meta-template',
  'timeline.empty-filter-title',
  'timeline.empty-filter-clear',
  'quick-log.failed.persistent-banner',
  'quick-log.failed.primary',
  'quick-log.failed.tertiary',
  'quick-log.snackbar.undo',
  'health.tab-title',
  'health.pet-hub.a11y',
  'health.pet-hub.edit-profile',
  'health.pet-hub.age-label',
  'health.pet-hub.breed-label',
  'health.pet-hub.weight-label',
  'health.pet-hub.add-weight',
  'health.pet-hub.quick-trackers-title',
  'health.pet-hub.quick-trackers-meta',
  'health.pet-hub.quick-trackers-a11y',
  'health.segments.0',
  'health.segments.1',
  'health.segments.2',
  'health.segments.3',
  'health.filter-chips.0',
  'health.filter-chips.1',
  'health.filter-chips.2',
  'health.empty.title',
  'health.empty.body',
  'health.empty.primary',
  'health.empty.secondary',
  'health.rows.current-section',
  'health.rows.previous-section',
  'health.rows.dhpp-title',
  'health.rows.dhpp-meta',
  'health.rows.weight-title',
  'health.rows.weight-meta',
  'health.rows.parasite-review-title',
  'health.rows.parasite-review-meta',
  'health.rows.parasite-review-subline',
  'health.rows.dhpp-template-title',
  'health.rows.dhpp-template-meta',
  'health.rows.vet-visit-title',
  'health.rows.vet-visit-meta',
  'health.vet-prep.title',
  'health.vet-prep.subtitle',
  'health.vet-prep.sample-date',
  'health.vet-prep.sample-time',
  'health.vet-prep.checklist.0',
  'health.vet-prep.checklist.1',
  'health.vet-prep.checklist.2',
  'health.vet-prep.checklist.3',
  'health.vet-prep.add-item',
  'health.vet-prep.hint',
  'health.pills.template',
  'health.pills.needs-vet-review',
  'health.pills.confirmed',
  'health.pills.completed',
  'health.template-row-subline',
  'health.add-record.sheet-title',
  'health.add-record.close',
  'health.add-record.form-cancel',
  'health.add-record.form-save',
  'health.add-record.hint-after-list',
  'health.add-record.section-main',
  'health.add-record.section-extra',
  'health.add-record.field-name',
  'health.add-record.field-date',
  'health.add-record.field-status',
  'health.add-record.default-date',
  'health.add-record.status-segments.0',
  'health.add-record.status-segments.1',
  'health.add-record.status-segments.2',
  'health.add-record.field-clinic',
  'health.add-record.field-note',
  'health.add-record.urgent-toggle',
  'health.add-record.urgent-off',
  'health.add-record.urgent-hint',
  'health.add-record.note-hint',
  'health.add-record.privacy-hint',
  'health.record-types.vaccination',
  'health.record-types.deworming',
  'health.record-types.prophylaxis',
  'health.record-types.vet-visit',
  'health.edit-record.screen-title',
  'health.edit-record.section-details',
  'health.edit-record.section-history',
  'health.edit-record.history-line',
  'health.edit-record.delete-action',
  'health.edit-record.delete-confirm.title',
  'health.edit-record.delete-confirm.body',
  'health.edit-record.delete-confirm.cancel',
  'health.edit-record.delete-confirm.destructive',
  'health.edit-record.delete-undo-toast',
  'health.detail.subtitle',
  'health.detail.date-label',
  'health.detail.date-value',
  'health.detail.status-label',
  'health.detail.clinic-label',
  'health.detail.clinic-value',
  'health.detail.note-label',
  'health.detail.note-value',
  'health.detail.stage-section',
  'health.detail.history-date',
  'health.detail.empty-value',
  'health.detail.states.loading.status',
  'health.detail.states.loading.title',
  'health.detail.states.loading.body',
  'health.detail.states.unavailable.status',
  'health.detail.states.unavailable.title',
  'health.detail.states.unavailable.body',
  'health.detail.states.not-found.status',
  'health.detail.states.not-found.title',
  'health.detail.states.not-found.body',
  'health.detail.states.error.status',
  'health.detail.states.error.title',
  'health.detail.states.error.body',
  'health.status-transitions.stages.0',
  'health.status-transitions.stages.1',
  'health.status-transitions.stages.2',
  'health.status-transitions.stages.3',
  'health.status-transitions.now-template',
  'health.status-transitions.complete-label',
  'health.status-transitions.hint',
  'health.status-transitions.a11y-template',
  'health.weight-entry.title',
  'health.weight-entry.value',
  'health.weight-entry.body',
  'health.weight-entry.action',
  'health.footer-hint',
  'more.puppy-summary.no-age',
  'more.puppy-profile.screen-title',
  'more.puppy-profile.missing-value',
  'more.screen-title',
  'more.sections.puppy',
  'more.sections.sharing',
  'more.sections.records',
  'more.sections.privacy',
  'more.sections.support',
  'more.puppy-summary.age-weeks',
  'more.puppy-summary.no-age',
  'more.rows.pet-settings',
  'more.rows.puppy-profile',
  'more.rows.quick-trackers',
  'more.rows.family',
  'more.rows.trainer-sitter',
  'more.rows.timeline',
  'more.rows.reminders',
  'more.rows.notifications',
  'more.rows.data-account',
  'more.rows.help',
  'more.rows.about',
  'more.rows.shareable-cards',
  'more.rows.puppyplan-plus',
  'more.rows.deferred',
  'more.about.version',
  'more.plus.subtitle',
  'more.quick-trackers.selected-count',
  'more.notifications.push-hint',
  'more.help.screen-title',
  'more.help.intro-title',
  'more.help.intro-body',
  'more.help.sections.topics',
  'more.help.sections.diagnostics',
  'more.help.topic-quick-log',
  'more.help.topic-sharing',
  'more.help.topic-privacy',
  'more.help.version-row',
  'more.help.support-code-row',
  'more.help.support-code-value',
  'more.help.contact-row',
  'more.help.contact-hint',
  'more.help.privacy-note',
  'paywall.title',
  'paywall.subtitle',
  'paywall.sections.features',
  'paywall.sections.plans',
  'paywall.features.0',
  'paywall.features.1',
  'paywall.features.2',
  'paywall.plan-yearly',
  'paywall.plan-yearly-a11y',
  'paywall.plan-monthly',
  'paywall.plan-lifetime',
  'paywall.primary',
  'paywall.secondary',
  'paywall.trial-status',
  'paywall.trial-note',
  'paywall.soft-lock-banner-title',
  'paywall.soft-lock-banner-body',
  'paywall.export-action',
  'paywall.soft-lock-title',
  'paywall.soft-lock-note',
  'paywall.legal',
  'sharing.family.accepted.header',
  'sharing.family.accepted.role-caregiver',
  'sharing.family.accepted.role-viewer',
  'sharing.family.accepted.what-included',
  'sharing.family.accepted.what-excluded',
  'sharing.family.accepted.caregiver-included-bullets.0',
  'sharing.family.accepted.caregiver-included-bullets.1',
  'sharing.family.accepted.caregiver-included-bullets.2',
  'sharing.family.accepted.caregiver-excluded-bullets.0',
  'sharing.family.accepted.caregiver-excluded-bullets.1',
  'sharing.family.accepted.disclosure',
  'sharing.family.accepted.accept',
  'sharing.family.accepted.decline',
  'sharing.family.accepted.neutral-unavailable',
  'sharing.common.disclosure-can-close',
  'sharing.family.today-prompt.title',
  'sharing.family.today-prompt.body',
  'sharing.family.manage.screen-title',
  'sharing.family.manage.section-members',
  'sharing.family.manage.section-invites',
  'sharing.family.manage.active-ago',
  'sharing.family.manage.pending-until',
  'sharing.family.manage.invite-cta',
  'sharing.family.manage.badge-owner',
  'sharing.family.manage.badge-caregiver',
  'sharing.family.manage.badge-pending',
  'sharing.sitter.screen-title',
  'sharing.sitter.subtitle',
  'sharing.sitter.subtitle-body',
  'sharing.sitter.section-who',
  'sharing.sitter.section-period',
  'sharing.sitter.period-start',
  'sharing.sitter.period-start-example',
  'sharing.sitter.period-end',
  'sharing.sitter.period-end-example',
  'sharing.sitter.section-checklist',
  'sharing.sitter.checklist-feeding',
  'sharing.sitter.checklist-walks',
  'sharing.sitter.checklist-potty',
  'sharing.sitter.checklist-meds',
  'sharing.sitter.checklist-training',
  'sharing.sitter.section-what-sitter-sees',
  'sharing.sitter.sitter-preview-bullets.0',
  'sharing.sitter.sitter-preview-bullets.1',
  'sharing.sitter.sitter-excluded',
  'sharing.sitter.disclosure',
  'sharing.sitter.enable-cta',
  'sharing.card-builder.screen-title',
  'sharing.card-builder.section-title',
  'sharing.card-builder.fields.0',
  'sharing.card-builder.fields.2',
  'sharing.card-builder.fields.6',
  'sharing.card-builder.footer-note',
  'sharing.card-builder.health-disclosure',
  'sharing.card-preview.a11y',
  'sharing.card-preview.share',
  'sharing.card-preview.footer',
  'sharing.card-management.screen-title',
  'sharing.card-management.section-active',
  'sharing.card-management.row-status-active',
  'sharing.card-management.public-link-disclosure',
  'sharing.card-management.sample-puppy-name',
  'sharing.card-management.sample-breed-age',
  'sharing.card-management.sample-vaccine-1',
  'sharing.card-management.sample-vaccine-2',
  'sharing.card-management.sample-active-date',
  'sharing.card-management.sample-recipient',
  'more.privacy.section-account-removal',
  'quick-log.sheet.title',
  'quick-log.sheet.dismiss',
  'quick-log.sheet.edit-trackers',
  'quick-log.sheet.edit-helper',
  'quick-log.sheet.unavailable.title',
  'quick-log.sheet.unavailable.body',
  'quick-log.sheet.unavailable.close',
  'quick-log.sheet.permission-denied.title',
  'quick-log.sheet.permission-denied.body',
  'quick-log.sheet.permission-denied.close',
  'quick-log.potty-subtype.title',
  'quick-log.potty-subtype.body',
  'quick-log.duplicate-warning.title',
  'quick-log.duplicate-warning.question',
  'quick-log.duplicate-warning.primary-alt',
  'quick-log.duplicate-warning.secondary',
  'states.revoked-or-expired.title',
  'states.revoked-or-expired.body-long',
  'states.revoked-or-expired.status',
  'states.revoked-or-expired.safety-label',
  'states.revoked-or-expired.safety-body',
  'states.revoked-or-expired.next-step-title',
  'states.revoked-or-expired.next-step-body',
  'states.revoked-or-expired.action',
] as const satisfies readonly I18nKey[];

export type PrimaryTabId = (typeof primaryTabs)[number]['id'];
export type PrimaryTabHref = (typeof primaryTabs)[number]['href'];
export type SettingsRoute = (typeof settingsRoutes)[number];
export type ShellI18nKey = (typeof shellI18nKeys)[number];
