// Generated by scripts/design/generate-tokens.mjs. Do not edit directly.
// Source: design-tokens.json.

export const tokens = {
  "business": {
    "noStreaksDays": 14,
    "quickLogPosition": "persistent central Add action opening a Quick Log / Schedule chooser, NOT a tab",
    "quickLogTrackersMax": 5,
    "tabs": [
      "diary",
      "pet",
      "more"
    ],
    "timing": {
      "accidentalDoubleTapWindowSeconds": 3,
      "duplicateCareWarningWindowSeconds": 60
    },
    "todayDailyCardsMax": 5
  },
  "color": {
    "surface": {
      "base": "#F6EFE3",
      "raised": "#FFFCF6",
      "sunken": "#ECE3D4",
      "overlay": "rgba(255,252,246,0.96)",
      "scrim": "rgba(40,30,22,0.34)"
    },
    "text": {
      "primary": "#2C2824",
      "secondary": "#6B6256",
      "tertiary": "#766C5A",
      "disabled": "#A99E8C",
      "onPrimary": "#FFF7EF",
      "onAccent": "#2C2824",
      "link": "#B26A3C"
    },
    "primary": {
      "50": "#FBF2EA",
      "100": "#F4DCC6",
      "200": "#ECC09C",
      "300": "#E0A271",
      "400": "#D08851",
      "500": "#C77F4F",
      "600": "#B26A3C",
      "700": "#8C5028",
      "800": "#5E3318",
      "900": "#4C2117"
    },
    "accent": {
      "100": "#FBEFD9",
      "300": "#F2D196",
      "500": "#E3A53C",
      "700": "#B07A1E"
    },
    "sage": {
      "100": "#E8EEDD",
      "300": "#BCD0A0",
      "500": "#84A06A",
      "700": "#5E7A3E"
    },
    "status": {
      "success": "#5C7A45",
      "successTint": "#E7EEDB",
      "warning": "#A87A2A",
      "warningTint": "#F7EAD2",
      "danger": "#A24A3C",
      "dangerTint": "#F4E4E0",
      "info": "#6E5862",
      "infoTint": "#ECE4E6"
    },
    "stroke": {
      "default": "#E4D9C8",
      "strong": "#C9BBA6",
      "dividerHairline": "rgba(228,217,200,0.6)",
      "focusRing": "#C77F4F"
    },
    "pill": {
      "template": {
        "fill": "#EFE6D7",
        "text": "#6B6256"
      },
      "needsVetReview": {
        "fill": "#F7EAD2",
        "text": "#7E5A18"
      },
      "confirmed": {
        "fill": "#E7EEDB",
        "text": "#44602E"
      },
      "completed": {
        "fill": "#E8E2D7",
        "text": "#6B6256"
      },
      "pending": {
        "fill": "#EFE6D7",
        "text": "#6B6256"
      },
      "failed": {
        "fill": "#F3E2DE",
        "text": "#7E3328"
      },
      "urgent": {
        "fill": "#F7EAD2",
        "text": "#7E5A18"
      }
    }
  },
  "component": {
    "trackerTile": {
      "twoCol": {
        "width": 168,
        "height": 96
      },
      "threeCol": {
        "width": 110,
        "height": 96
      },
      "min": {
        "width": 88,
        "height": 88
      },
      "icon": 28
    },
    "fab": {
      "size": 56,
      "radius": 999,
      "fill": "primary/600",
      "icon": "28pt white",
      "elevation": "elev/2"
    },
    "tabBar": {
      "height": 49,
      "icon": 24,
      "active": "primary/700 + filled icon"
    },
    "bottomSheet": {
      "minHeight": 460,
      "radiusTop": 16,
      "dragHandle": {
        "width": 36,
        "height": 4
      },
      "elevation": "elev/2"
    },
    "listItem": {
      "minHeight": 56,
      "padding": "12pt vertical, 16pt horizontal"
    },
    "snackbar": {
      "radius": 12,
      "padding": "12pt vertical, 16pt horizontal",
      "elevation": "elev/1",
      "durationDefault": "4s",
      "durationWithAction": "6s"
    },
    "pill": {
      "height": 24,
      "padding": "4pt vertical, 8pt horizontal",
      "radius": 8,
      "icon": 14
    }
  },
  "elevation": {
    "0": {
      "shadow": "none",
      "border": "1px solid #E4D9C8",
      "androidElevation": 0
    },
    "1": {
      "x": 0,
      "y": 2,
      "blur": 8,
      "color": "#46321E",
      "opacity": 0.07,
      "androidElevation": 2
    },
    "2": {
      "x": 0,
      "y": -4,
      "blur": 16,
      "color": "#46321E",
      "opacity": 0.1,
      "androidElevation": 6
    },
    "3": {
      "x": 0,
      "y": 8,
      "blur": 24,
      "color": "#46321E",
      "opacity": 0.14,
      "androidElevation": 12
    }
  },
  "haptic": {
    "light": {
      "ios": "impactLight",
      "android": "KEYBOARD_TAP",
      "trigger": "Tap on Tracker Tile, open sheet"
    },
    "medium": {
      "ios": "impactMedium",
      "android": "LONG_PRESS",
      "trigger": "Drag handle, segment switch"
    },
    "success": {
      "ios": "notificationSuccess",
      "android": "CONFIRM",
      "trigger": "Quick Log saved, vaccine confirmed"
    },
    "warning": {
      "ios": "notificationWarning",
      "android": "REJECT",
      "trigger": "Duplicate detected (60-second window)"
    },
    "error": {
      "ios": "notificationError",
      "android": "REJECT",
      "trigger": "Failed save, permission denied"
    }
  },
  "icon": {
    "specs": {
      "size": 24,
      "stroke": 1.75,
      "caps": "rounded",
      "iosSource": "SF Symbols (regular weight, regular variant)",
      "androidSource": "Material Symbols Outlined (size 24, weight 400, fill 0)",
      "activeState": "fill 1 (only in Tab Bar active)"
    },
    "coreMvp": [
      "nav.today",
      "nav.health",
      "nav.more",
      "action.quick_log",
      "action.add",
      "action.share",
      "action.edit",
      "action.delete",
      "action.search",
      "potty.outside",
      "potty.inside",
      "potty.poop",
      "feeding.bowl",
      "feeding.water",
      "sleep.moon",
      "zoomies.spark",
      "training.paw",
      "household.home",
      "person.solo",
      "person.cluster",
      "person.vet",
      "person.trainer",
      "med.vaccine",
      "med.deworming",
      "med.pill",
      "med.weight",
      "med.vet_visit",
      "status.template",
      "status.review",
      "status.confirmed",
      "status.completed",
      "status.urgent_flag"
    ],
    "utility": [
      "chevron.right",
      "chevron.down",
      "close.x",
      "check",
      "info.circle",
      "lock.shield"
    ],
    "extended": [
      "ui.bell",
      "ui.bell.slash",
      "ui.wifi.slash",
      "ui.book",
      "ui.doc.text",
      "ui.stethoscope",
      "ui.phone",
      "ui.lock",
      "ui.gear",
      "ui.checkmark.seal",
      "ui.checkmark.circle",
      "ui.exclamation.circle",
      "ui.info.card",
      "ui.paw.filled",
      "person.crop.circle.badge.checkmark"
    ]
  },
  "layout": {
    "screenPaddingPhone": 16,
    "screenPaddingY": 24,
    "screenPaddingTablet": 24,
    "sectionGap": 24,
    "cardPadding": 16,
    "tapTargetMin": 44,
    "tapTargetThumbZone": 56,
    "tapGapMin": 8,
    "maxContentWidth": 560,
    "tabBarHeight": 49,
    "bottomInsetFab": 120,
    "appBarCollapsed": 44,
    "appBarExpanded": 96
  },
  "motion": {
    "duration": {
      "instant": 80,
      "fast": 160,
      "base": 240,
      "slow": 360
    },
    "easing": {
      "standard": "cubic-bezier(0.4, 0, 0.2, 1)",
      "decel": "cubic-bezier(0.0, 0, 0.2, 1)",
      "accel": "cubic-bezier(0.4, 0, 1, 1)",
      "emphasized": "cubic-bezier(0.3, 0, 0, 1)"
    },
    "reducedMotion": {
      "transformFallback": "opacity 0→1, motion/fast",
      "celebrationFallback": "static badge, no particle",
      "sheetFallback": "cross-fade instead of slide-up",
      "disabled": [
        "parallax",
        "large-title bounce"
      ]
    }
  },
  "radius": {
    "sm": 8,
    "md": 12,
    "lg": 16,
    "full": 999
  },
  "space": {
    "0": 0,
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 20,
    "6": 24,
    "8": 32,
    "10": 40,
    "14": 56
  },
  "typography": {
    "fontFamily": {
      "display": "Lora",
      "text": "Nunito",
      "ios": "SF Pro Text",
      "android": "Roboto",
      "mono": [
        "SF Mono",
        "Roboto Mono",
        "monospace"
      ]
    },
    "fontWeight": {
      "regular": 400,
      "semibold": 600
    },
    "scale": {
      "display": {
        "fontSize": 34,
        "lineHeight": 41,
        "fontWeight": 600,
        "dynamicType": "largeTitle",
        "letterSpacing": 0
      },
      "title1": {
        "fontSize": 28,
        "lineHeight": 34,
        "fontWeight": 600,
        "dynamicType": "title1",
        "letterSpacing": 0
      },
      "title2": {
        "fontSize": 22,
        "lineHeight": 28,
        "fontWeight": 600,
        "dynamicType": "title2",
        "letterSpacing": 0
      },
      "title3": {
        "fontSize": 20,
        "lineHeight": 25,
        "fontWeight": 600,
        "dynamicType": "title3",
        "letterSpacing": 0
      },
      "headline": {
        "fontSize": 17,
        "lineHeight": 22,
        "fontWeight": 600,
        "dynamicType": "headline",
        "letterSpacing": 0
      },
      "body": {
        "fontSize": 17,
        "lineHeight": 24,
        "fontWeight": 400,
        "dynamicType": "body",
        "letterSpacing": 0
      },
      "bodyEmph": {
        "fontSize": 17,
        "lineHeight": 24,
        "fontWeight": 600,
        "dynamicType": "body",
        "letterSpacing": 0
      },
      "callout": {
        "fontSize": 16,
        "lineHeight": 22,
        "fontWeight": 400,
        "dynamicType": "callout",
        "letterSpacing": 0
      },
      "subheadline": {
        "fontSize": 15,
        "lineHeight": 20,
        "fontWeight": 400,
        "dynamicType": "subheadline",
        "letterSpacing": 0
      },
      "footnote": {
        "fontSize": 13,
        "lineHeight": 18,
        "fontWeight": 400,
        "dynamicType": "footnote",
        "letterSpacing": 0
      },
      "caption": {
        "fontSize": 12,
        "lineHeight": 16,
        "fontWeight": 400,
        "dynamicType": "caption1",
        "letterSpacing": 0
      },
      "code": {
        "fontSize": 15,
        "lineHeight": 20,
        "fontWeight": 400,
        "family": "mono",
        "letterSpacing": 0
      }
    },
    "rules": [
      "Минимум читаемого текста — 16pt (Callout). Body = 17pt по умолчанию.",
      "Line-length 65–75 символов.",
      "Tabular numerals для всех числовых данных (weight, dose, time).",
      "Letter-spacing 0 для всех размеров.",
      "Weight Light/Thin запрещён."
    ]
  }
} as const;

export const businessTiming = tokens.business.timing;

export type DesignTokens = typeof tokens;
export type BusinessTimingTokens = typeof businessTiming;
